name: CI/CD

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and npm cache
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            functions/package-lock.json

      - name: Install dependencies
        run: |
          npm ci
          npm ci --prefix functions

      - name: lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and npm cache
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            functions/package-lock.json

      - name: Install dependencies
        run: |
          npm ci
          npm ci --prefix functions

      - name: build
        run: npm run build

      - name: Upload hosting
        uses: actions/upload-artifact@v3
        with:
          name: sveltekit-build
          path: build/

      - name: Upload functions
        uses: actions/upload-artifact@v3
        with:
          name: functions-lib
          path: functions/lib/

  svelte-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node and npm cache
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Svelte Check
        run: npm run check

  vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node and npm cache
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Vitest
        run: npm run test:unit

  playwright:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node and npm cache
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            functions/package-lock.json

      - name: Install dependencies
        run: |
          npm ci
          npm ci --prefix functions

      - name: Install Playwright
        run: npx playwright install

      - name: Download hosting
        uses: actions/download-artifact@v3
        with:
          name: sveltekit-build
          path: build/

      - name: Download functions
        uses: actions/download-artifact@v3
        with:
          name: functions-lib
          path: functions/lib/

      - name: Playwright
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: [build, vitest, svelte-check, playwright]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node and npm cache
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            functions/package-lock.json

      - name: Install dependencies
        run: |
          npm ci
          npm ci --prefix functions

      - name: Download hosting
        uses: actions/download-artifact@v3
        with:
          name: sveltekit-build
          path: build/

      - name: Download functions
        uses: actions/download-artifact@v3
        with:
          name: functions-lib
          path: functions/lib/

      - name: deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --message \"${{ github.event.head_commit.message }}\"
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WTMCROBOTICS_WEBSITE }}

  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    needs: [deploy]

    steps:
      - uses: actions/checkout@v3

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: https://wtmcrobotics-website.web.app
          budgetPath: lighthouserc.yml
          uploadArtifacts: true
          temporaryPublicStorage: true
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
